/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ancode.ui;

import org.ancode.util.ErrorMessage;
import org.ancode.util.BrowserUtil;
import org.ancode.util.Log;
import org.ancode.util.PersistenceUtils;
import org.ancode.util.FileLockUtil;
import atg.taglib.json.util.JSONException;
import atg.taglib.json.util.JSONObject;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JCheckBox;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.GroupLayout;

import org.ancode.comm.ComboBoxRenderer;

public class LoginPanel extends JPanel {

    private MainFrame mainFrame = MainFrame.getMainFrame();
    private JSONObject memberList = null;

    private JCheckBox RememberCheckBox;
    private JButton btnLogin;
    private JButton btnRegister;
    private JComboBox combAccount;
   // private JComboBox comboLoginStatus;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel lblAccountMenage;
    private JLabel lblForgetPassword;
    private JLabel lblLogo;
    private JLabel lblRegister;
    private JPasswordField textPassword;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {

    	ResourceBundle bundle = ResourceBundle.getBundle("res/res");
        MainFrame.getMainFrame().setIBackground(bundle.getString("mx.defLoginBg"));

        initComponents();
        this.setVisible(true);

        initLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        lblLogo = new JLabel(new ImageIcon(getClass().getResource("/res/images/lockpic.png")));
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        RememberCheckBox = new JCheckBox();
        //comboLoginStatus = new JComboBox();
        btnLogin = new JButton();
        btnRegister = new JButton();
        combAccount = new JComboBox();
        textPassword = new JPasswordField();
        lblRegister = new JLabel();
        lblForgetPassword = new JLabel();
        lblAccountMenage = new JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(255, 555));

        lblLogo.setFont(lblLogo.getFont());
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogo.setPreferredSize(new java.awt.Dimension(255, 100));

        jLabel1.setFont(new java.awt.Font("宋体", 0, 12)); 
        jLabel1.setForeground(java.awt.Color.white);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("res/res"); 
        jLabel1.setText(bundle.getString("mx.acount")); 

        jLabel2.setFont(new java.awt.Font("宋体", 0, 12)); 
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText(bundle.getString("mx.password")); 

        RememberCheckBox.setFont(new java.awt.Font("宋体", 0, 15)); 
        RememberCheckBox.setSelected(true);
        RememberCheckBox.setText(bundle.getString("mx.res.rememberPassword")); 

        
        btnLogin.setFont(new java.awt.Font("宋体", 0, 15)); 
        btnLogin.setText(bundle.getString("mx.login")); 
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLogin(evt);
            }
        });
        
        btnRegister.setFont(new java.awt.Font("宋体", 0, 15)); 
        btnRegister.setText(bundle.getString("mx.register")); 
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //toLogin(evt);
            }
        });

        combAccount.setEditable(true);
        combAccount.setFont(new java.awt.Font("宋体", 0, 15)); 
        combAccount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combAccountItemStateChanged(evt);
            }
        });

        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });
        textPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPasswordFocusGained(evt);
            }
        });

        lblRegister.setFont(new java.awt.Font("宋体", 0, 12));
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/icon/bigIcon.png")));
        lblRegister.setText("注册密讯");
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });

        lblForgetPassword.setFont(new java.awt.Font("宋体", 0, 12)); 
        lblForgetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/icon/account_find.png"))); 
        lblForgetPassword.setText("找回密码");
        lblForgetPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblForgetPasswordKeyPressed(evt);
            }
        });

        lblAccountMenage.setFont(new java.awt.Font("宋体", 0, 12)); 
        lblAccountMenage.setIcon(new ImageIcon(getClass().getResource("/res/images/icon/account_m.png"))); 
        lblAccountMenage.setText("管理帐号");
        lblAccountMenage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccountMenageMouseClicked(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRegister)
                            .addGap(91, 91, 91))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RememberCheckBox)
                                .addComponent(combAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(0, 42, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGap(20)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel1)
                    .addGap(11, 11, 11)
                    .addComponent(combAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addGap(12, 12, 12)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(RememberCheckBox)
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    		.addComponent(btnLogin)
                    		.addComponent(btnRegister))
                    
                    .addContainerGap(208, Short.MAX_VALUE))
            );

        lblLogo.getAccessibleContext().setAccessibleName("logo");
    }// </editor-fold>//GEN-END:initComponents

    private void toLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLogin
        // TODO add your handling code here:
        String account = this.combAccount.getSelectedItem().toString();
        if(!FileLockUtil.getFileLock(account)) {
            ErrorMessage.show(account+" 已登陆");
            return;
        }
        if (mainFrame.getMap() == null) {
            Map map = new HashMap();
            mainFrame.setMap(map);
        }

        Log.println("to login");
        Map loginMap = new HashMap();
        loginMap.put("account", account);
        loginMap.put("password", this.textPassword.getText().toString());
        loginMap.put("verifyCode", this.textPassword.getText().toString());
        loginMap.put("rememberPassword", this.RememberCheckBox.isSelected());
     /*   int loginStatusIndex = this.comboLoginStatus.getSelectedIndex();
        String loginStatus = "online";
        switch (loginStatusIndex) {
            case 1: {
                loginStatus = "callme";
                break;
            }
            case 2: {
                loginStatus = "busy";
                break;
            }
            case 3: {
                loginStatus = "hidden";
                break;
            }
            case 4: {
                loginStatus = "silent";
                break;
            }
        }*/
        loginMap.put("loginStatus", 0);

        LoginProcessPanel loginProcessPanel = new LoginProcessPanel();
        try {
            mainFrame.getMap().put("loginMap", loginMap);
            loginProcessPanel.login();
        } catch (Exception ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainFrame.getMap().put("loginPanel", this);
        mainFrame.setContentPane(loginProcessPanel);
        mainFrame.validate();

    }//GEN-LAST:event_toLogin

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        // TODO add your handling code here:
        this.toLogin(evt);
    }//GEN-LAST:event_textPasswordActionPerformed

    private void combAccountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combAccountItemStateChanged
        // TODO add your handling code here:
        String account = this.combAccount.getSelectedItem().toString();
        try {
            if (memberList != null && !memberList.isNull(account)) {
                this.textPassword.setText(memberList.getString(account));
            }
        } catch (JSONException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_combAccountItemStateChanged

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
         BrowserUtil.openURL("http://zc.qq.com/chs/index.html");
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void lblForgetPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblForgetPasswordKeyPressed
        // TODO add your handling code here:
        BrowserUtil.openURL("http://imsafe.qq.com/");
    }//GEN-LAST:event_lblForgetPasswordKeyPressed

    private void lblAccountMenageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountMenageMouseClicked
        // TODO add your handling code here:
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("删除帐号");
        JMenuItem clearPasswordItem = new JMenuItem("重置密码");
        popupMenu.add(deleteItem);
        popupMenu.add(clearPasswordItem);
        Component c = (Component) evt.getSource();
        popupMenu.show(c, -1, c.getHeight());
        deleteItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                String account = (String) combAccount.getSelectedItem();
                combAccount.removeItemAt(combAccount.getSelectedIndex());
                Map m = new HashMap();
                m.put("account", account);
                PersistenceUtils.getInstance().update(m);
            }
        });

        clearPasswordItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                String account = (String) combAccount.getSelectedItem();
                combAccount.removeItemAt(combAccount.getSelectedIndex());
                Map m = new HashMap();
                m.put("account", account);
                m.put("password", "");
                PersistenceUtils.getInstance().update(m);
            }
        });
    }//GEN-LAST:event_lblAccountMenageMouseClicked

    private void textPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPasswordFocusGained
        // TODO add your handling code here:
        String account = this.combAccount.getSelectedItem().toString();
        if (memberList != null && memberList.isNull(account)) {
            this.textPassword.setText("");
        }

    }
    
    // End of variables declaration//GEN-END:variables
    public boolean checkInput(String input) {
		boolean ret = true;
		char[] temp = input.toCharArray();
		int len = temp.length;
		for (int i = 0; i < len; i++) {
			if ((temp[i] <= 'z' && temp[i] >= 'a') || (temp[i] <= 'Z' && temp[i] >= 'A')
					|| (temp[i] <= '9' && temp[i] >= '0')) {
			} else {
				JOptionPane.showMessageDialog(this, "密码只能为数字和字母组合", "密码错误",JOptionPane.ERROR_MESSAGE);
				ret = false;
				break;
			}
		}
		return ret;
	}
    private void initLogin() {
        ComboBoxRenderer cbr = new ComboBoxRenderer();
        this.combAccount.setRenderer(cbr);

        memberList = PersistenceUtils.getInstance().loadMemberList();
        if (memberList != null) {
//            for (Object s : memberList.toHashMap().keySet()) {
//                this.combAccount.addItem(s);
//            }
            Set set = memberList.toHashMap().keySet();
            Object[] obj = set.toArray();
            Log.println(obj.length);
            for (int i = set.size() - 1; i > -1; i--) {
                this.combAccount.addItem(obj[i]);
            }
        }

    }
}
