/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ancode.ui;

import java.awt.*;
import java.awt.event.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import org.ancode.comm.Auth;
import org.ancode.service.LoginService;
import org.ancode.util.ErrorMessage;
import org.ancode.util.Log;
import org.ancode.util.ThreadUtil;


public class MainFrame extends javax.swing.JFrame {

    private static MainFrame mainFrame;
    private Map map = new HashMap();

    public Map getMap() {
        return map;
    }

    public void setMap(Map map) {
        this.map = map;
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setFont(new Font("宋体 ", Font.PLAIN, 15));
        this.setTitle("密讯");
        //System.out.println(getClass().getResource("/").getPath());
        mainFrame = this;
        this.setContentPane(new LoginPanel());
        this.setIconImage(Toolkit.getDefaultToolkit().createImage(
                getClass().getResource("/res/images/icon/bigIcon.png")));
        //getClass().getResource("/res/images/icon/bigIcon.png")));
    }

    public static MainFrame getMainFrame() {
        return mainFrame;
    }

    public void setIBackground(String path) {
        if (path != null) {
        	//System.out.println(this.getClass().getClassLoader());
            ImageIcon img = new ImageIcon(this.getClass().getClassLoader().getResource(path));
            JLabel background = new JLabel(img);
            background.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
            this.getLayeredPane().removeAll();
            this.getLayeredPane().add(background, new Integer(Integer.MIN_VALUE));
            this.validate();
        } else {
            this.getLayeredPane().removeAll();
            this.validate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("密讯");
        setBounds(new Rectangle(1000, 100, 0, 0));
        setForeground(Color.white);
        setName("密讯"); // NOI18N
        setPreferredSize(new Dimension(255, 555));
        addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowIconified(WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (Auth.getPsessionid() == null) {
            ThreadUtil.shutdown();
            System.exit(0);
            return;
        }
        int optionType = JOptionPane.showConfirmDialog(null, "按 [是] 退出程序，[否] 隐藏到系统托盘", "是否退出程序？", JOptionPane.YES_NO_OPTION);
        Log.println("optionType:" + optionType + " yes:" + JOptionPane.YES_OPTION + " no:" + JOptionPane.NO_OPTION);
        if (optionType == JOptionPane.YES_OPTION) {
            ThreadUtil.shutdown();
            System.exit(0);
        } else {
            if (TrayFactory.getInstance().isIsSupported()) {
                this.setVisible(false);
            } else {
                ErrorMessage.show("系统不支持系统托盘！");
            }
        }
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowIconified(WindowEvent evt) {
        // TODO add your handling code here:
        if (TrayFactory.getInstance().isIsSupported()) {
            this.setExtendedState(JFrame.NORMAL);
            this.setState(JFrame.NORMAL);
            this.setVisible(false);
        }
    }//GEN-LAST:event_formWindowIconified

    private void formWindowClosed(WindowEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        LoginService.getInstance().logout();
        ThreadUtil.shutdown();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void initSystemTray() {
        com.sun.awt.AWTUtilities.setWindowOpacity(this, 0.3F);
        TrayFactory.getInstance().createTray(this, "/res/images/icon/icon.png", "密讯");
    }
}
